# House Prediction

##### Downloading the data

In [8]:
import pandas as pd
import numpy as np
df = pd.read_csv("data/USA Housing Dataset.csv")
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-09 00:00:00,376000.0,3.0,2.00,1340,1384,3.0,0,0,3,1340,0,2008,0,9245-9249 Fremont Ave N,Seattle,WA 98103,USA
1,2014-05-09 00:00:00,800000.0,4.0,3.25,3540,159430,2.0,0,0,3,3540,0,2007,0,33001 NE 24th St,Carnation,WA 98014,USA
2,2014-05-09 00:00:00,2238888.0,5.0,6.50,7270,130017,2.0,0,0,3,6420,850,2010,0,7070 270th Pl SE,Issaquah,WA 98029,USA
3,2014-05-09 00:00:00,324000.0,3.0,2.25,998,904,2.0,0,0,3,798,200,2007,0,820 NW 95th St,Seattle,WA 98117,USA
4,2014-05-10 00:00:00,549900.0,5.0,2.75,3060,7015,1.0,0,0,5,1600,1460,1979,0,10834 31st Ave SW,Seattle,WA 98146,USA

In [51]:
other_input = ['bedrooms', 'bathrooms', 'floors', 'condition']
to_scale = ['sqft_living','sqft_lot','sqft_above',"yr_built"]

### Building the model

In [66]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(df[to_scale])
scaled_input = scaler.transform(df[to_scale])
df[to_scale] = scaled_input
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-09 00:00:00,3.760000e+05,3.0,2.00,-0.839427,-0.371138,3.0,0,0,3,-0.570491,0,1.247670,0,9245-9249 Fremont Ave N,Seattle,WA 98103,USA
1,2014-05-09 00:00:00,8.000000e+05,4.0,3.25,1.458545,4.034632,2.0,0,0,3,1.983850,0,1.214118,0,33001 NE 24th St,Carnation,WA 98014,USA
2,2014-05-09 00:00:00,2.238888e+06,5.0,6.50,5.354651,3.214701,2.0,0,0,3,5.327715,850,1.314775,0,7070 270th Pl SE,Issaquah,WA 98029,USA
3,2014-05-09 00:00:00,3.240000e+05,3.0,2.25,-1.196657,-0.384518,2.0,0,0,3,-1.199787,200,1.214118,0,820 NW 95th St,Seattle,WA 98117,USA
4,2014-05-10 00:00:00,5.499000e+05,5.0,2.75,0.957169,-0.214165,1.0,0,0,5,-0.268614,1460,0.274658,0,10834 31st Ave SW,Seattle,WA 98146,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4135,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,-0.661856,-0.232424,1.0,0,0,4,-0.373110,0,-0.564146,1979,501 N 143rd St,Seattle,WA 98133,USA
4136,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,-0.714083,-0.198610,2.0,0,0,3,-0.431163,0,0.408866,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4137,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,0.904942,-0.214193,2.0,0,0,3,1.368486,0,1.281222,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4138,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,-0.056028,-0.224898,1.0,0,0,3,-0.883978,1020,0.106897,0,5148 S Creston St,Seattle,WA 98178,USA
4139,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,-0.682747,-0.183863,2.0,0,0,4,-0.396331,0,0.643731,0,18717 SE 258th St,Covington,WA 98042,USA

In [89]:
# all = np.concatenate((df[to_scale].values, df[other_input].values), axis = 1)
all = pd.concat([df[to_scale], df[other_input]], axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(all, df['price'], test_size=0.3, random_state=42)

model = LinearRegression().fit(X_train, Y_train)

### Testing the model

In [131]:
prediction = model.predict(pd.DataFrame([[0.2, -0.4, 0.5, -0.9, 2,3,1,3]], columns=all.columns))
print(f"The house price is : {prediction[0]}")

The house price is : 811409.9082207135

### Evaluating the model

In [132]:
prediction = model.predict(X_test)

In [133]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print(f"Mean absolute error: {mean_absolute_error(Y_test, prediction)}")
print(f"Mean squared error: {mean_squared_error(Y_test, prediction)}")
print(f"r2 score: {r2_score(Y_test, prediction)}")

Mean absolute error: 167697.80665351384
Mean squared error: 75681486191.61543
r2 score: 0.47795818114810196